config/routes.rb
Rails.application.routes.draw do
    root "artists#index"

    resources :artists do
      resources :songs
    end

    resources :photos

    namespace :api do
      resources :artists do
        resources :songs, only: [:create, :update, :destroy]
    end
  end
end

#  get "artists" => "artists#index"
#  get "artists/new" => "artists#new", as: :new_artist
#  get "artists/:id" => "artists#show", as: :artist

#  post "artists" => "artists#create"
#  get "artists/:id/edit" => "artists#edit", as: :edit_artist

#  patch "artists/:id" => "artists#update"
#  delete "artists/:id" => "artists#destroy"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
  validates :album, presence: true
  validates :year, presence: true, length: { maximum:4 }

end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController

   skip_before_action :verify_authenticity_token

  def index
    artist = Artist.all
    render status: 200, json: artist
  end

  def show
    artist = Artist.find(params[:id])
    render status: 200, json: artist
  end

  def create
    artist = Artist.new(artist_params)

    if artist.save
      render status: 200, json: artist
    else
      render status: 422, json: {
        errors: artist.errors
      }.to_json
    end
  end

  def destroy
    artist = Artist.find(params[:id])
    artist.destroy

    render status: 200, json: {
      message: "Artist deleted"
    }.to_json
  end

  def update
    artist = Artist.find(params[:id])
    if artist.update(artist_params)
      render status: 200, json: artist
    else
      render status: 500, json: {
        message: "Artist could not be updated",
        errors:artist.errors
      }.to_json
    end
  end

    private
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController

     skip_before_action :verify_authenticity_token

  def create
    song_params = params.require(:song).permit(:name, :year, :album, :artist_id)
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)

    if @song.save
      render status: 201, json: @song
    else
      render status: 422, json: {
        errors: artist.errors
      }.to_json
    end
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy

    render status: 200, json: {
      message: "Song deleted",
    }.to_json
  end

  def update
    song = Song.find(params[:id])
    if song.update(song_params)
      render status: 200, json: song
    else
      render status: 422, json: {
        message: "Song could not be updated",
        errors:song.errors
      }.to_json
    end
  end

  private
  def song_params
    song_params = params.require(:song).permit(:name, :year, :album, :artist_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
    end

  def show
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
    @songs = @artist.songs
    @song = Song.new
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to edit_artist_path(@artist), notice: "Artist successfully
      created"
    else
      render "new"
    end
  end

  def edit
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
    @songs = @artist.songs
    @song = Song.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update_attributes(artist_params)
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to edit_artist_path(@artist), notice: "Artist successfully
      updated"
    else
      render "edit"
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @song = Song.find(params[:id])
    @song.destroy
    @artist.destroy
    redirect_to @artist
  end

private

  def artist_params
    params.require(:artist).permit(:name, photo_ids:[])
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
      @artist = photo.artist
        photo.destroy
          redirect_to edit_artist_path(@artist), notice: "Photo successfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

def index
  @artist = Artist.find(params[:artist_id])
  @songs = @artist.songs
end

def show
  @artist = Artist.find(params[:artist_id])
  @song = @artist.songs.find(params[:id])
end

def new
  @artist = Artist.find(params[:artist_id])
  @song = @artist.songs.build
end

def edit
  @artist = Artist.find(params[:artist_id])
  @song = @artist.songs.find(params[:id])
end

def create
  song_params = params.require(:song).permit(:name, :year, :album, :artist_id)
  @artist = Artist.find(params[:artist_id])
  @song = @artist.songs.new(song_params)


    respond_to do |format|
    if @song.save
      format.html {redirect_to @artist, notice: "New Song Added!"}
      format.json {render :show, status: :created, location: @artist }
      format.js
    else
      format.html {render @artist.id, notice: "Song not Added, Please try again"}
      format.json {render json: @artist.errors, status: :unprocessable_entity }
      format.js
    end
  end
end

  def update
    song_params = params.require(:song).permit(:name, :year, :album, :artist_id)
    @song = Song.find(params[:id])
    @song.update_attributes(song_params)
    redirect_to artist_song_path(@song), notice: "Song Updated"
  end

def destroy
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
    @song.destroy

    redirect_to artists_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
  <%= form_for @artist, html: { multipart: true } do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>


  <label>Photos</label>

<div class="form-group">
  <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
</div>

<div id="photos">
  <%= render 'photos/list' %>
</div>

<br>
  <%= f.submit (@artist.new_record? ? "Create" : "Update") %>

<% end %>

app/views/artists/_form_song.html.erb
<%= form_for [@artist, @song], remote:true do |f| %>
  <div class="form-group">

      <%= f.text_field :name, placeholder: "Song name", class: "form-control" %>
      <br>
      <%= f.text_field :album, placeholder: "Album name", class: "form-control" %>
      <br>
      <%= f.text_field :year, placeholder: "What year was it released?", class: "form-control" %>
      <br>
      <%= f.label :artist_id %>

    <br>
      <%= f.collection_select :artist_id, Artist.all, :id, :name %>
    <br>

  <div class="actions">
    <br>
      <%= f.submit (@song.new_record? ? "Add Song" : "Update") %>

    <br>
  </div>
<% end %>

app/views/artists/create.js.erb
debugger

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>

<br>

<%= link_to 'Back', artists_path, class: "btn btn-primary" %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name,
  artist_path(artist.id) %></p>
<% end %>

<hr>

<%= link_to "[New Artist]", new_artist_path,class: "btn btn-primary" %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form" %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
    <br>
<h4> List of Songs </h4>
    <br>
    <ul>
      <% @artist.songs.each do |song| %>
        <li class ="Songs"> <p id="SongName"><b>Song Title:</b> <%= song.name %></p><p id="SongAlbum"><b>Album:</b> <%= song.album %></p> <p id="SongYear"><b>Released In:</b> <%= song.year %></p> <hr> </li>
      <% end %>
    </ul>


<!-- Photos -->
<h3><strong>Photos</strong></h3>
<% @artist.photos.each do |photo| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= image_tag photo.image.thumbnail %>
  </div>
</div>
<% end %>

<hr>

<h3>Add New Song to <%= "#{@artist.name}" %> </h3>
  <br>
    <%= render "form_song" %>
  <br>

<%= link_to "[Edit]", edit_artist_path(@artist.id), class: "btn btn-primary" %>
<%= link_to "[Delete]", artist_path(@artist.id), class: "btn btn-primary",method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <%= yield %>


  <%= link_to "[All Artists]", root_path,  class: "btn btn-primary" %>

  </body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">Delete</span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/songs/_form.html.erb
<%= form_for [:artist, @song] do |f| %>
  <div class="form-group">

  <div class="form-group">
    <label>Song name</label>
    <%= f.text_field :name, placeholder: "Song name", class: "form-control" %>
    <%= f.text_field :album, placeholder: "Album name", class: "form-control" %>
    <%= f.text_field :year, placeholder: "What year was it released?", class: "form-control" %>
    <%= f.label :artist_id %>
    <%= f.collection_select :artist_id, Artist.all, :id, :name %>
  </div>


  <div class="actions">
    <%= f.submit (@song.new_record? ? "Add Song" : "Update") %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/songs/show.html.erb
<h1><%= "#{@song.name}" %></h1>

<p>Album:      <%= @song.album %></p>
<p>Year:        <%= @song.year %></p>

<%= link_to "Edit this Song", edit_artist_song_path(@song.id) %>

<br><br>
<hr>
<%= link_to "Delete this Song", artist_song_path(@song.id), method: :delete, data: { confirm: "Are You Sure You Want to Rewrite History?" } %>